Fixed accordion component
js-tasks-ru/htmlcss-20210916_ivan-talalaev pull request #7
Opened 2021-09-27 14:08 UTC by IvanTale

2021-09-27 14:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-27 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-28 12:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-28 20:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 19:44 UTC, GSemikozov requested changes

2021-09-29 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion > .accordion__summary {
вложенность здесь не обязательно указывать

2021-09-29 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion > .accordion__summary-wrapped {
и тут

2021-09-29 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion > .accordion__summary::after {
и тут

2021-09-29 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > .accordion__summary::after {
и тут

2021-09-29 19:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 19:58 UTC, IvanTale commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > .accordion__summary::after {
Предыдущие кейсы я исправил и проверил, всё исправно работает. А вот тут, кроме как такого селектора `.accordion[open] .accordion__summary::after ` ничего не работает. Надо было лишь знак `>` убрать, или же как-то иначе?

2021-09-29 20:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 20:03 UTC, IvanTale commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > .accordion__summary::after {
@GSemikozov Я исправил, всё кроме последнего замечания, убрал лишь `>` . По крайней мере у меня всё работает в таком виде xD

2021-09-29 20:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > .accordion__summary::after {
а, сорри, тут все правильно, да

2021-09-29 20:27 UTC, GSemikozov approved these changes

2021-09-29 20:27 UTC, merged